### ISSUE TITLE
Consider adding newlines in XML documents for better git diffs

### ISSUE THREAD

**Issue by dhimmel** [elifesciences/elife-article-xml#2]
Thanks @gmaciocci for letting me know about this repository. Very cool and useful to have the XML for all eLife articles in one place.

As of https://github.com/elifesciences/elife-article-xml/commit/ae02816d9b5986d7e5fa02d5cd974354364e37cc, it looks like the XML files don't contain any newlines. This helps them be most compact, but is not ideal for tracking via git. Do XML files ever get modified in this repository (as opposed to just created)? If so, it may make sense to add newlines, such that git diffs can show just the lines that have changed.

If I am not mistaken, this could also help reduce the repository size since diffs would be smaller ([reference](https://www.linkedin.com/pulse/git-internals-how-works-kaushik-rangadurai/)).

**Comment by Melissa37** [comment]
Hi @dhimmel Thanks for your request/comment.

I'll pull in @gnott, who will best able to answer this question as he populates the repositories with the XML we produce in the production process. I always look at "pretty XML" because it's easier for my eyes to parse :-) , but I know this causes problems for other processes and hence the no line breaks. @gnott is the best able to talk to this and also whether it's possible to change the XML in the repo.

**Comment by gnott** [comment]
Yes, I had meant to reply. Many years ago, we tested prettified XML and there were some situations where the additional whitespace produced incorrect rendering of the article. 

One example I remember was in the license paragraph, it had an inline `<ext-link>` tag (I think) to the license URL, the prettifier would add a new line for this tag, and after rendering the pretty XML we got a space character before a comma in that paragraph. I think we actually changed the wording to avoid the comma in the end anyway.

I think it is possible that tags inside sentences of text will end up with additional whitespace after rendering from pretty XML. That is what stopped us from altering the XML in any way from the original.

**Comment by dhimmel** [comment]
Thanks @gnott for the explanation. So if I'm understanding correctly, prettifying the XML was adding newlines before tags inside text. Then when the text was extracted, it would contain extra spaces, since the newlines were converted to spaces.

This sounds really unfortunate that XML (or specific XML formatters) are unable to add insignificant newlines for document aesthetics without affecting the text source. The [comments here](https://bugs.python.org/issue14465#msg304872) attest to this limitation of XML:

> 1. Whitespaces are significant in XML. Pretty-printed XML is different from the original XML to an XML parser. For some applications some whitespaces around tags are not significant. But this depends on the application and in different parts of the document whitespaces can have different meaning. For example the document can contain a metadata with insignificant whitespaces and marked up text with significant whitespaces. There is a special attribute named `xml:space` that can signal the meaning of whitespaces for the part of a document. https://www.w3.org/TR/xml/#sec-white-space
> 
> 2. In HTML whitespaces around `<P>` are insignificant, but whitespaces around `<I>` are significant. Whitespaces inside `<PRE>...</PRE>` are significant.

So for now my understanding is that prettifying could potentially change the text content. I'll reopen this issue if I come across a pretty XML formatted that guarantees to round-trip XML without any functional differences.

**Comment by Melissa37** [comment]
>I'll reopen this issue if I come across a pretty XML formatted that guarantees to round-trip XML without any functional differences.

That would be fantastic if you could let us know if you find any such tools @dhimmel Thank you!
